SELECT CONCAT(NAME,"(",SUBSTRING(OCCUPATION,1,1),")") 
AS withFirstLetter
FROM OCCUPATIONS
ORDER BY withFirstLetter;

SELECT CONCAT('There are a total of ',COUNT(OCCUPATION),' ',LOWER(OCCUPATION),'s.') AS numberOfOccupations
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY numberOfOccupations ASC